# ------------------------------------------------------------------------------
# KNN Regressor configuration file for in-silico experiment
# ------------------------------------------------------------------------------

ml_model: "kNNRegressorAL"

model_parameters:
  k : 10
  length_scale : 1.0
  noise_floor : 0.000001
  distance_penalty : 0.0

grid_search:
  perform_grid_search: true
  every_n_points: 20  # Perform grid search every N acquired points
