# ------------------------------------------------------------------------------
# Benchmark configuration file for Active Learning Regressor experiments
# ------------------------------------------------------------------------------
SEED: null

experiment_name: "6D/hartmann_gpr_40cy_5pts_1stage_3_2"
experiment_notes: "Benchmarking the Hartmann 6D function"

# --------------------------------------------------------------
# Ground truth data configuration
ground_truth_file: "hartmann6d_lhs_1M.csv"
experiment_evidence: null

# --------------------------------------------------------------
# Search space and target variable configuration
search_space_variables:
  - "x1"
  - "x2"
  - "x3"
  - "x4"
  - "x5"
  - "x6"

target_variables:
  - "y"

# --------------------------------------------------------------
# Data scaling configuration
data_scaler: "StandardScaler"
scaler_params: null

# --------------------------------------------------------------
# Cycles parameters
n_cycles: 40
init_batch_size: 5
init_sampling: "random"

landscape_penalization: null  # radius: 0.25, strength: 1.0

batch_selection:
  # highest_landscape | constant_liar | kriging_believer | local_penalization
  method: "highest_landscape"
  method_params: # if `null` uses default params for the selected mode (see documentation for details)
    # eg. for highest_landscape:
    percentile: 95
    sampling_method: "voronoi"

# Multi-stage acquisition protocol configuration
acquisition_protocol:
  stage_1:
    cycles: 40
    acquisition_modes: ['exploration_mutual_info', 'expected_improvement']
    n_points: [2, 3]  # Number of points to acquire for each mode in stage 1
  # stage_2:
  #   cycles: 40
  #   acquisition_modes: ['expected_improvement']
  #   n_points: [2]  # Number of points to acquire for each mode in stage 2
  # stage_3:
  #   cycles: 10
  #   acquisition_modes: ['exploration_mutual_info']
  #   n_points: [2]  # Number of points to acquire for each mode in stage 3
  # stage_4:
  #   cycles: 20
  #   acquisition_modes: ['expected_improvement']
  #   n_points: [2]  # Number of points to acquire for each mode in stage 4

# --------------------------------------------------------------
# Adaptive refinement configuration
adaptive_refinement: # refinement parameters disabled if null
  method: "lhs"  # method to sample the points for the refinement (either 'lhs' or 'sobol')
  refinement_noise_std: 0.0
  refinement_step: 10  # number of points acquired after which to perform refinement
  refinement_centroids: 3  # number of centroids to use for the refinement (chosen via fps)
  refinement_batch_size: 250  # number of points to sample around each centroid during refinement
  half_side_length_strategy: 'density'  # strategy to determine the half-side length of the hypercube around each centroid (either 'fixed' or 'density')
  half_side_length_strategy_params:  # parameters for the half-side length strategy (if using 'fixed', provide 'base_fraction'; if using 'density', provide 'density_scale' and 'max_half_side')
    base_fraction: 0.3
    k_neighbors: 5
    density_scale: 0.5
    max_half_side: 0.5
  refinement_filtering_min_distance: 0.0001  # minimum distance from existing points for refined points to be kept (in the scaled space)
