# ------------------------------------------------------------------------------
# Target function and train set configuration for the benchmark experiment.
# ------------------------------------------------------------------------------

# Function settings
function_parameters:
  function: "Ackley6D"  # "Hartmann" or "Ackley" or "StyblinskiTang"
  custom: false  # whether to use a custom function defined in a separate file (if true, the 'function' parameter will be ignored and the function will be imported from the specified file)
  n_dimensions: null  # number of dimensions of the function (if null, it will be inferred from the bounds or from the ground truth file if provided)
  bounds: null  # bounds of the function (if null, it will be inferred from the ground truth file if provided or set to default bounds for the selected function)

# Train set configuration (initial points)
train_set_parameters:
  n_samples: 50000
  method: "lhs"
  val_size: null
  negate: true
  noise_std: 0.0
